### ISSUE TITLE
A check for compatible OS

### ISSUE THREAD

**Issue by Rafii2198** [LemonCaramel/Mica#2]
Now I know a user that is on let's say a Mac install this (or maybe does on accident) but if a modpack author would want to add this mod to a modpack it would cause issues for said users as the game will crash, without giving any useful info, there will be no crash report and logs will just cut off.

I want to suggest adding a check that would basically disable the mod if the needed OS is not present to not cause issues. If possible, maybe in the case of incompatibility, the config screen would just say something like "Your operating system is not compatible with Mica thus it is disabled for safety" instead of the default config screen.

Modpack author's would benefit as they would be free to add Mica to their modpack (it is such a nice mod tbh) and it would not cause any crashes for Mac users (I am one of them and just got a report, we were trying to find a culprit, and then I noticed the user is on Mac) as well as individual users, someone could add this mod in a big batch with other mods and it is so small many people would probably not think that it could cause crashes.

**Comment by LemonCaramel** [comment]
At the start of the mod, it checks the operating system. However, due to my mistake, it doesn't seem to be working correctly.
