### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by misaka10384** [LemonCaramel/Mica#3]
该mod在我的系统上遇到了错误 Minecraft甚至无法启动
log: https://mclo.gs/P0SOCaQ
操作系统版本: windows11 canary 26002.1010
游戏版本: Minecraft forge 1.20.1

mod :
yet-another-config-lib-forge-3.2.1+1.20
mica-1.0.1-forge

**Comment by LemonCaramel** [comment]
Hello, I don't know how to read Chinese :(
and... this is not a bug in Mica, it's a problem in YACL.
https://github.com/isXander/YetAnotherConfigLib/issues/124
