### ISSUE TITLE
[Feature Request] Better Sodium support

### ISSUE THREAD

**Issue by Felix14-v2** [LemonCaramel/Mica#4]
### Description
Window border and corners are still visible in fullscreen:
![image](https://github.com/LemonCaramel/Mica/assets/75726196/6cd0b27a-c6e9-4b45-9f59-ca6b2f0d18c9)
![image](https://github.com/LemonCaramel/Mica/assets/75726196/dd1a8408-6a6f-4e77-854e-087990676581)
![image](https://github.com/LemonCaramel/Mica/assets/75726196/3c76e363-9bff-4ee5-90a7-cc9a5dd8a9ed)

**Comment by LemonCaramel** [comment]
Something seems off. When the game switches to Fullscreen mode, DWM should be disabled.
Are you using any other mod related to fullscreen?

**Comment by Felix14-v2** [comment]
> Are you using any other mod related to fullscreen?

No, the only mod I tested with was Sodium
![image](https://github.com/LemonCaramel/Mica/assets/75726196/5fec2a2d-d830-4826-8471-995597b892c1)

Iirc, Sodium modifies the game window to protect the game from the Nvidia driver hacks on systems with an Nvidia GPU.

**Comment by Felix14-v2** [comment]
Yes, seems that this is Sodium, I don't see the issue when running Minecraft with Intel Graphics

**Comment by LemonCaramel** [comment]
I also use Sodium, but I haven't experienced this problem.
I might need to investigate this problem a bit further.

**Comment by Felix14-v2** [comment]
> I also use Sodium, but I haven't experienced this problem.

Do you have an Nvidia GPU? I think you should launch the game with it to reproduce the problem.

**Comment by LemonCaramel** [comment]
Yes, I'm using an NVIDIA GPU.
Could you let me know what version of the minecraft you are using?

**Comment by LemonCaramel** [comment]
I've requested testing from three friends who are using Windows 11 and NVIDIA GPU, and they did not encounter this issue.
I suspect the external program is preventing the game from properly switching to full screen mode.

For now, since it doesn't appear to be an issue with Mica, I'll close the issue.

**Comment by Felix14-v2** [comment]
But I still can reproduce the issue... And even without Sodium. Minecraft 1.20.4
<details>
 <summary>Screenshots</summary>

![image](https://github.com/LemonCaramel/Mica/assets/75726196/bd0e5927-07cf-48c3-b83f-8e32d9a6a9b1)
![image](https://github.com/LemonCaramel/Mica/assets/75726196/ac17aacc-39d7-404a-9a99-5becdc81e232)
</details>

I updated my system, graphics driver, tried different launcher – no difference. Maybe that's because of MUX graphics on my laptop? I suspect your friends don't have MUX.

**Comment by LemonCaramel** [comment]
Was not this issue present when you are not using Mica?

**Comment by Felix14-v2** [comment]
It isn't, occurs only with Mica with the modified corners curvature setting. Probably with others too, but I can't see the effect in fullscreen

**Comment by LemonCaramel** [comment]
Mica works using the DWM API. Typically, Windows disables the DWM when a game is in fullscreen mode. Therefore, when the game switches to fullscreen, Mica should also be auto disabled.
For the above reason, I think this is not an issue with Mica.

It may or may not be helpful, but I have made changes to disable Mica when switching to fullscreen mode. You can download the test artifact by clicking on this link. https://github.com/LemonCaramel/Mica/actions/runs/7853859960

**Comment by Felix14-v2** [comment]
> It may or may not be helpful, but I have made changes to disable Mica when switching to fullscreen mode.

It worked, thanks! Now the problem is gone

The weird thing is that I never installed external programs like RivaTuner or even GeForce Experience to modify the game window behavior.
